import {
  Document,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  HeadingLevel,
  BorderStyle,
  Packer,
  ShadingType,
  PageBreak,
} from "docx";
import type { RedlineResult, RedlineItem } from "@/types";

const SEVERITY_COLORS: Record<string, string> = {
  critical: "FF0000",
  major: "FF8C00",
  minor: "FFD700",
  informational: "4169E1",
};

const SEVERITY_BG: Record<string, string> = {
  critical: "FFE0E0",
  major: "FFF0E0",
  minor: "FFFFF0",
  informational: "E8F0FE",
};

/**
 * Generate a professional redline DOCX report.
 */
export async function generateRedlinedDocx(
  result: RedlineResult,
  originalText: string
): Promise<Buffer> {
  const doc = new Document({
    creator: "RedlineIQ",
    title: "RedlineIQ LOI Analysis Report",
    description: "AI-Powered LOI Redline Analysis",
    sections: [
      {
        properties: {},
        children: [
          // Legal disclaimer
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
            border: {
              top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
            },
            shading: { type: ShadingType.CLEAR, color: "auto", fill: "FFF9E6" },
            children: [
              new TextRun({
                text: "DISCLAIMER: ",
                bold: true,
                color: "B8860B",
                size: 18,
              }),
              new TextRun({
                text: "RedlineIQ is not a law firm and does not provide legal advice. All analysis, deal scores, and recommendations are automated suggestions based on commercial real estate industry benchmarks. Users should consult qualified legal and real estate professionals before acting on any findings. Users are solely responsible for their decisions regarding any LOI or lease transaction.",
                color: "666666",
                size: 18,
              }),
            ],
          }),
          // Title page
          ...buildTitlePage(result),
          // Executive summary
          ...buildExecutiveSummary(result),
          // Redline items
          ...buildRedlineSection(result.redlines),
          // Missing provisions
          ...buildMissingProvisionsSection(result.missing_provisions),
          // Negotiation strategy
          ...buildNegotiationStrategy(result.negotiation_strategy),
          // Footer
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
            children: [
              new TextRun({
                text: "Generated by RedlineIQ - AI-Powered CRE LOI Analysis",
                italics: true,
                color: "888888",
                size: 18,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

function buildTitlePage(result: RedlineResult): Paragraph[] {
  const riskColors: Record<string, string> = {
    low: "228B22",
    medium: "FF8C00",
    high: "FF4500",
    critical: "FF0000",
  };

  return [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2400, after: 200 },
      children: [
        new TextRun({
          text: "REDLINEIQ",
          bold: true,
          size: 48,
          color: "1E3A5F",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: "LOI ANALYSIS REPORT",
          bold: true,
          size: 32,
          color: "444444",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: `Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
          size: 22,
          color: "666666",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Deal Score: ", bold: true, size: 28 }),
        new TextRun({
          text: `${result.summary.deal_score}/10`,
          bold: true,
          size: 28,
          color: result.summary.deal_score >= 7 ? "228B22" : result.summary.deal_score >= 4 ? "FF8C00" : "FF0000",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Risk Level: ", bold: true, size: 28 }),
        new TextRun({
          text: result.summary.risk_level.toUpperCase(),
          bold: true,
          size: 28,
          color: riskColors[result.summary.risk_level] || "000000",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: `Property Type: ${result.summary.property_type || "N/A"}  |  Deal Type: ${result.summary.deal_type || "N/A"}`,
          size: 22,
          color: "666666",
        }),
      ],
    }),
    new Paragraph({
      children: [new PageBreak()],
    }),
  ];
}

function buildExecutiveSummary(result: RedlineResult): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
      children: [
        new TextRun({ text: "Executive Summary", bold: true, color: "1E3A5F" }),
      ],
    }),
  ];

  // Key concerns
  if (result.summary.key_concerns.length > 0) {
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 100 },
        children: [new TextRun({ text: "Key Concerns", bold: true, color: "CC0000" })],
      })
    );
    for (const concern of result.summary.key_concerns) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: concern, size: 22 })],
        })
      );
    }
  }

  // Strengths
  if (result.summary.strengths.length > 0) {
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 100 },
        children: [new TextRun({ text: "Strengths", bold: true, color: "228B22" })],
      })
    );
    for (const strength of result.summary.strengths) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: strength, size: 22 })],
        })
      );
    }
  }

  // Stats
  const criticalCount = result.redlines.filter((r) => r.severity === "critical").length;
  const majorCount = result.redlines.filter((r) => r.severity === "major").length;
  const minorCount = result.redlines.filter((r) => r.severity === "minor").length;

  paragraphs.push(
    new Paragraph({
      spacing: { before: 200, after: 100 },
      children: [
        new TextRun({ text: "Issues Found: ", bold: true, size: 22 }),
        new TextRun({ text: `${criticalCount} Critical`, color: "FF0000", size: 22 }),
        new TextRun({ text: ` | ${majorCount} Major`, color: "FF8C00", size: 22 }),
        new TextRun({ text: ` | ${minorCount} Minor`, color: "DAA520", size: 22 }),
        new TextRun({ text: ` | ${result.missing_provisions.length} Missing Provisions`, color: "4169E1", size: 22 }),
      ],
    })
  );

  return paragraphs;
}

function buildRedlineSection(redlines: RedlineItem[]): Paragraph[] {
  if (redlines.length === 0) return [];

  const paragraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
      children: [
        new TextRun({ text: "Redline Items", bold: true, color: "1E3A5F" }),
      ],
    }),
  ];

  // Sort by severity
  const sorted = [...redlines].sort((a, b) => {
    const order = { critical: 0, major: 1, minor: 2, informational: 3 };
    return (order[a.severity] ?? 4) - (order[b.severity] ?? 4);
  });

  for (const item of sorted) {
    const severityColor = SEVERITY_COLORS[item.severity] || "000000";
    const bgColor = SEVERITY_BG[item.severity] || "FFFFFF";

    paragraphs.push(
      new Paragraph({
        spacing: { before: 300, after: 50 },
        shading: { type: ShadingType.CLEAR, color: "auto", fill: bgColor },
        border: {
          left: { style: BorderStyle.SINGLE, size: 6, color: severityColor },
        },
        children: [
          new TextRun({
            text: `[${item.severity.toUpperCase()}] `,
            bold: true,
            color: severityColor,
            size: 22,
          }),
          new TextRun({
            text: `${item.section} - ${item.category}`,
            bold: true,
            size: 22,
          }),
        ],
      }),
      new Paragraph({
        spacing: { after: 50 },
        children: [
          new TextRun({ text: "Issue: ", bold: true, size: 20 }),
          new TextRun({ text: item.issue, size: 20 }),
        ],
      }),
      new Paragraph({
        spacing: { after: 50 },
        children: [
          new TextRun({ text: "Original: ", bold: true, size: 20, color: "888888" }),
          new TextRun({ text: `"${item.original_text}"`, italics: true, size: 20, color: "888888" }),
        ],
      }),
      new Paragraph({
        spacing: { after: 50 },
        children: [
          new TextRun({ text: "Recommendation: ", bold: true, size: 20 }),
          new TextRun({ text: item.recommendation, size: 20 }),
        ],
      }),
      new Paragraph({
        spacing: { after: 50 },
        children: [
          new TextRun({ text: "Suggested Language: ", bold: true, size: 20, color: "228B22" }),
          new TextRun({ text: `"${item.suggested_language}"`, italics: true, size: 20, color: "228B22" }),
        ],
      }),
      new Paragraph({
        spacing: { after: 100 },
        children: [
          new TextRun({ text: "Market Benchmark: ", bold: true, size: 18, color: "666666" }),
          new TextRun({ text: item.market_benchmark, size: 18, color: "666666" }),
        ],
      })
    );
  }

  return paragraphs;
}

function buildMissingProvisionsSection(
  provisions: RedlineResult["missing_provisions"]
): Paragraph[] {
  if (provisions.length === 0) return [];

  const paragraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
      children: [
        new TextRun({ text: "Missing Provisions", bold: true, color: "1E3A5F" }),
      ],
    }),
  ];

  for (const provision of provisions) {
    const importanceColor =
      provision.importance === "critical" ? "FF0000" : provision.importance === "recommended" ? "FF8C00" : "4169E1";

    paragraphs.push(
      new Paragraph({
        spacing: { before: 200, after: 50 },
        children: [
          new TextRun({
            text: `[${provision.importance.toUpperCase()}] `,
            bold: true,
            color: importanceColor,
            size: 22,
          }),
          new TextRun({ text: provision.provision, bold: true, size: 22 }),
        ],
      }),
      new Paragraph({
        spacing: { after: 50 },
        children: [
          new TextRun({ text: "Rationale: ", bold: true, size: 20 }),
          new TextRun({ text: provision.rationale, size: 20 }),
        ],
      }),
      new Paragraph({
        spacing: { after: 100 },
        children: [
          new TextRun({ text: "Suggested Language: ", bold: true, size: 20, color: "228B22" }),
          new TextRun({ text: `"${provision.suggested_language}"`, italics: true, size: 20, color: "228B22" }),
        ],
      })
    );
  }

  return paragraphs;
}

function buildNegotiationStrategy(
  strategy: RedlineResult["negotiation_strategy"]
): Paragraph[] {
  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
      children: [
        new TextRun({ text: "Negotiation Strategy", bold: true, color: "1E3A5F" }),
      ],
    }),
    new Paragraph({
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Overall Approach: ", bold: true, size: 22 }),
        new TextRun({ text: strategy.overall_approach, size: 22 }),
      ],
    }),
    new Paragraph({
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Opening Position: ", bold: true, size: 22 }),
        new TextRun({ text: strategy.opening_position, size: 22 }),
      ],
    }),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
      children: [new TextRun({ text: "Hard Lines (Do Not Concede)", bold: true, color: "CC0000" })],
    }),
    ...strategy.hard_lines.map(
      (line) =>
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: line, size: 22 })],
        })
    ),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
      children: [new TextRun({ text: "Concession Priorities (Give First If Needed)", bold: true, color: "228B22" })],
    }),
    ...strategy.concession_priorities.map(
      (item) =>
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: item, size: 22 })],
        })
    ),
  ];
}

/**
 * Generate a PDF summary. For MVP, returns an HTML string that can be
 * rendered to PDF on the client, or served as a downloadable HTML report.
 */
export async function generatePdfSummary(
  result: RedlineResult
): Promise<Buffer> {
  const criticalCount = result.redlines.filter((r) => r.severity === "critical").length;
  const majorCount = result.redlines.filter((r) => r.severity === "major").length;
  const topItems = result.redlines
    .filter((r) => r.severity === "critical" || r.severity === "major")
    .slice(0, 5);

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>RedlineIQ LOI Summary</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a2e; }
    .header { text-align: center; border-bottom: 3px solid #1E3A5F; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: #1E3A5F; margin: 0; font-size: 28px; }
    .header p { color: #666; margin: 5px 0; }
    .score-section { display: flex; justify-content: space-around; margin: 30px 0; text-align: center; }
    .score-box { padding: 20px; border-radius: 12px; min-width: 150px; }
    .score-box.deal-score { background: ${result.summary.deal_score >= 7 ? "#e8f5e9" : result.summary.deal_score >= 4 ? "#fff3e0" : "#ffebee"}; }
    .score-box.risk { background: ${{ low: "#e8f5e9", medium: "#fff3e0", high: "#ffebee", critical: "#ffcdd2" }[result.summary.risk_level]}; }
    .score-box .value { font-size: 36px; font-weight: bold; }
    .score-box .label { font-size: 14px; color: #666; margin-top: 5px; }
    .stats { display: flex; gap: 15px; margin: 20px 0; }
    .stat { padding: 10px 15px; border-radius: 8px; font-size: 14px; font-weight: 600; }
    .stat.critical { background: #ffebee; color: #c62828; }
    .stat.major { background: #fff3e0; color: #e65100; }
    .stat.missing { background: #e3f2fd; color: #1565c0; }
    .items h2 { color: #1E3A5F; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
    .item { padding: 15px; margin: 10px 0; border-left: 4px solid; border-radius: 4px; background: #fafafa; }
    .item.critical { border-color: #f44336; }
    .item.major { border-color: #ff9800; }
    .item .severity { font-weight: bold; text-transform: uppercase; font-size: 12px; }
    .item .issue { margin: 5px 0; }
    .item .rec { color: #2e7d32; font-style: italic; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>RedlineIQ</h1>
    <p>LOI Analysis Summary Report</p>
    <p>${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div style="background: #fff9e6; border: 1px solid #e6d590; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; font-size: 11px; color: #8B7500; line-height: 1.5;">
    <strong>DISCLAIMER:</strong> RedlineIQ is not a law firm and does not provide legal advice. All analysis, deal scores, and recommendations are automated suggestions based on commercial real estate industry benchmarks. Consult qualified legal and real estate professionals before acting on any findings.
  </div>

  <div class="score-section">
    <div class="score-box deal-score">
      <div class="value">${result.summary.deal_score}/10</div>
      <div class="label">Deal Score</div>
    </div>
    <div class="score-box risk">
      <div class="value">${result.summary.risk_level.toUpperCase()}</div>
      <div class="label">Risk Level</div>
    </div>
  </div>

  <div class="stats">
    <div class="stat critical">${criticalCount} Critical</div>
    <div class="stat major">${majorCount} Major</div>
    <div class="stat missing">${result.missing_provisions.length} Missing</div>
  </div>

  ${result.summary.key_concerns.length > 0 ? `
  <div class="items">
    <h2>Key Concerns</h2>
    <ul>${result.summary.key_concerns.map((c) => `<li>${escapeHtml(c)}</li>`).join("")}</ul>
  </div>` : ""}

  ${topItems.length > 0 ? `
  <div class="items">
    <h2>Top Issues</h2>
    ${topItems.map((item) => `
    <div class="item ${item.severity}">
      <span class="severity" style="color: ${({ critical: "#c62828", major: "#e65100", minor: "#f9a825", informational: "#1565c0" } as Record<string, string>)[item.severity] || "#333"}">${item.severity}</span>
      - ${escapeHtml(item.section)}
      <div class="issue">${escapeHtml(item.issue)}</div>
      <div class="rec">${escapeHtml(item.recommendation)}</div>
    </div>`).join("")}
  </div>` : ""}

  <div class="footer">
    Generated by RedlineIQ - AI-Powered CRE LOI Analysis<br>
    Download the full DOCX report for complete redline details and suggested language.
  </div>
</body>
</html>`;

  return Buffer.from(html, "utf-8");
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
