/**
 * PowerPoint (PPTX) Export
 * 
 * Creates professional presentation slides from calculator results.
 * Uses pptxgenjs for generation.
 */

import PptxGenJS from 'pptxgenjs';
import { CanonicalExportData, ExportMetric, SensitivityTable } from './types';

// Color constants (matching brand)
const COLORS = {
  primary: '6B7F6E',
  accent: 'C97D60',
  text: '4A4A4A',
  lightBg: 'F5F1E9',
  white: 'FFFFFF',
  headerBg: '6B7F6E',
};

/**
 * Format value for display
 */
function formatValue(metric: ExportMetric): string {
  if (typeof metric.value === 'string') return metric.value;
  
  switch (metric.format) {
    case 'currency':
      return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(metric.value);
    case 'percent':
      return `${(metric.value * 100).toFixed(2)}%`;
    case 'multiple':
      return `${metric.value.toFixed(2)}x`;
    default:
      return String(metric.value);
  }
}

/**
 * Create title slide
 */
function createTitleSlide(pptx: PptxGenJS, data: CanonicalExportData): void {
  const slide = pptx.addSlide();
  
  // Background
  slide.background = { color: COLORS.white };
  
  // Title
  slide.addText(data.reportTitle, {
    x: 0.5,
    y: 2,
    w: 9,
    h: 1,
    fontSize: 36,
    bold: true,
    color: COLORS.primary,
    fontFace: 'Calibri',
  });
  
  // Subtitle (address or deal name)
  const subtitle = data.address
    ? [data.address.address, data.address.city, data.address.state, data.address.zipCode]
        .filter(Boolean)
        .join(', ')
    : data.address?.dealName || '';
  
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.5,
      y: 3,
      w: 9,
      h: 0.5,
      fontSize: 18,
      color: COLORS.text,
      fontFace: 'Calibri',
    });
  }
  
  // Date
  slide.addText(`Report Date: ${data.exportDate}`, {
    x: 0.5,
    y: 3.6,
    w: 9,
    h: 0.4,
    fontSize: 12,
    color: '888888',
    fontFace: 'Calibri',
  });
  
  // Footer
  slide.addText('Generated by DealCalc', {
    x: 0.5,
    y: 5,
    w: 9,
    h: 0.3,
    fontSize: 10,
    color: '888888',
    fontFace: 'Calibri',
  });
}

/**
 * Create key metrics slide
 */
function createMetricsSlide(pptx: PptxGenJS, data: CanonicalExportData): void {
  const slide = pptx.addSlide();
  
  // Title
  slide.addText('Key Metrics', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.6,
    fontSize: 28,
    bold: true,
    color: COLORS.primary,
    fontFace: 'Calibri',
  });
  
  // Create metric cards (2x2 or 2x3 grid)
  const metrics = data.keyMetrics.slice(0, 6);
  const cols = 2;
  const cardWidth = 4.3;
  const cardHeight = 1.2;
  const startX = 0.5;
  const startY = 1.2;
  const gapX = 0.2;
  const gapY = 0.2;
  
  metrics.forEach((metric, idx) => {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const x = startX + col * (cardWidth + gapX);
    const y = startY + row * (cardHeight + gapY);
    
    // Card background
    slide.addShape('rect', {
      x,
      y,
      w: cardWidth,
      h: cardHeight,
      fill: { color: COLORS.lightBg },
      line: { color: 'E0E0E0', width: 1 },
    });
    
    // Label
    slide.addText(metric.label, {
      x: x + 0.15,
      y: y + 0.15,
      w: cardWidth - 0.3,
      h: 0.35,
      fontSize: 12,
      color: '666666',
      fontFace: 'Calibri',
    });
    
    // Value
    slide.addText(formatValue(metric), {
      x: x + 0.15,
      y: y + 0.5,
      w: cardWidth - 0.3,
      h: 0.5,
      fontSize: 24,
      bold: true,
      color: metric.isWarning ? COLORS.accent : COLORS.primary,
      fontFace: 'Calibri',
    });
  });
}

/**
 * Create warnings slide (if any)
 */
function createWarningsSlide(pptx: PptxGenJS, data: CanonicalExportData): void {
  if (data.warnings.length === 0) return;
  
  const slide = pptx.addSlide();
  
  // Title
  slide.addText('Risk Flags', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.6,
    fontSize: 28,
    bold: true,
    color: COLORS.accent,
    fontFace: 'Calibri',
  });
  
  // Warning list
  const warnings = data.warnings.slice(0, 8);
  warnings.forEach((warning, idx) => {
    slide.addText(`• ${warning.message}`, {
      x: 0.5,
      y: 1.2 + idx * 0.5,
      w: 9,
      h: 0.45,
      fontSize: 14,
      color: warning.severity === 'error' ? COLORS.accent : COLORS.text,
      fontFace: 'Calibri',
    });
  });
}

/**
 * Create sources & uses slide
 */
function createSourcesUsesSlide(pptx: PptxGenJS, data: CanonicalExportData): void {
  // Find sources and uses sections
  const sourcesSection = data.assumptions.find(s => s.title.toLowerCase().includes('source'));
  const usesSection = data.assumptions.find(s => s.title.toLowerCase().includes('use'));
  
  if (!sourcesSection && !usesSection) return;
  
  const slide = pptx.addSlide();
  
  // Title
  slide.addText('Sources & Uses', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.6,
    fontSize: 28,
    bold: true,
    color: COLORS.primary,
    fontFace: 'Calibri',
  });
  
  // Sources table (left)
  if (sourcesSection && Array.isArray(sourcesSection.data)) {
    const sourcesData = sourcesSection.data as ExportMetric[];
    const tableData = [
      [{ text: 'Sources', options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } }, 
       { text: 'Amount', options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } }],
      ...sourcesData.map(m => [m.label, formatValue(m)]),
    ];
    
    slide.addTable(tableData as PptxGenJS.TableRow[], {
      x: 0.5,
      y: 1.1,
      w: 4.3,
      fontSize: 12,
      fontFace: 'Calibri',
      color: COLORS.text,
      border: { color: 'E0E0E0', pt: 1 },
      align: 'left',
    });
  }
  
  // Uses table (right)
  if (usesSection && Array.isArray(usesSection.data)) {
    const usesData = usesSection.data as ExportMetric[];
    const tableData = [
      [{ text: 'Uses', options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } }, 
       { text: 'Amount', options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } }],
      ...usesData.map(m => [m.label, formatValue(m)]),
    ];
    
    slide.addTable(tableData as PptxGenJS.TableRow[], {
      x: 5,
      y: 1.1,
      w: 4.3,
      fontSize: 12,
      fontFace: 'Calibri',
      color: COLORS.text,
      border: { color: 'E0E0E0', pt: 1 },
      align: 'left',
    });
  }
}

/**
 * Create cash flow slide (if available)
 */
function createCashFlowSlide(pptx: PptxGenJS, data: CanonicalExportData): void {
  if (!data.cashFlowTable || data.cashFlowTable.rows.length === 0) return;
  
  const slide = pptx.addSlide();
  const { title, columns, rows } = data.cashFlowTable;
  
  // Title
  slide.addText(title, {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.6,
    fontSize: 28,
    bold: true,
    color: COLORS.primary,
    fontFace: 'Calibri',
  });
  
  // Build table data
  const headerRow = columns.map(col => ({ 
    text: col, 
    options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } 
  }));
  
  // Limit rows to fit on slide
  const displayRows = rows.slice(0, 10);
  const dataRows = displayRows.map(row => 
    columns.map(col => String(row[col] ?? ''))
  );
  
  slide.addTable([headerRow, ...dataRows] as PptxGenJS.TableRow[], {
    x: 0.3,
    y: 1.0,
    w: 9.4,
    fontSize: 9,
    fontFace: 'Calibri',
    color: COLORS.text,
    border: { color: 'E0E0E0', pt: 1 },
    align: 'center',
  });
}

/**
 * Create sensitivity analysis slide
 */
function createSensitivitySlide(pptx: PptxGenJS, table: SensitivityTable): void {
  const slide = pptx.addSlide();
  
  // Title
  slide.addText(table.title || 'Sensitivity Analysis', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.6,
    fontSize: 28,
    bold: true,
    color: COLORS.primary,
    fontFace: 'Calibri',
  });
  
  // Build table data
  const headerRow = [
    { text: `${table.rowHeader} \\ ${table.colHeader}`, options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } },
    ...table.colLabels.map(col => ({ text: col, options: { bold: true, fill: { color: COLORS.headerBg }, color: 'FFFFFF' } })),
  ];
  
  const dataRows = table.cells.map((row, rowIdx) => [
    { text: table.rowLabels[rowIdx], options: { bold: true } },
    ...row.map(cell => ({
      text: cell.secondaryValue ? `${cell.primaryValue}\n${cell.secondaryValue}` : String(cell.primaryValue),
      options: cell.isHighlighted ? { fill: { color: COLORS.lightBg } } : {},
    })),
  ]);
  
  slide.addTable([headerRow, ...dataRows] as PptxGenJS.TableRow[], {
    x: 0.5,
    y: 1.1,
    w: 9,
    fontSize: 10,
    fontFace: 'Calibri',
    color: COLORS.text,
    border: { color: 'E0E0E0', pt: 1 },
    align: 'center',
  });
}

/**
 * Create disclaimer slide
 */
function createDisclaimerSlide(pptx: PptxGenJS, data: CanonicalExportData): void {
  const slide = pptx.addSlide();
  
  slide.addText('Disclaimer', {
    x: 0.5,
    y: 2,
    w: 9,
    h: 0.5,
    fontSize: 18,
    bold: true,
    color: COLORS.text,
    fontFace: 'Calibri',
  });
  
  slide.addText(data.disclaimer, {
    x: 0.5,
    y: 2.6,
    w: 9,
    h: 2,
    fontSize: 12,
    color: '888888',
    fontFace: 'Calibri',
    italic: true,
  });
  
  slide.addText('dealcalc.com', {
    x: 0.5,
    y: 5,
    w: 9,
    h: 0.3,
    fontSize: 10,
    color: COLORS.primary,
    fontFace: 'Calibri',
  });
}

/**
 * Export data to PowerPoint presentation
 */
export async function exportToPptx(data: CanonicalExportData): Promise<void> {
  const pptx = new PptxGenJS();
  
  // Set metadata
  pptx.author = 'DealCalc';
  pptx.title = data.reportTitle;
  pptx.subject = 'Investment Analysis Report';
  pptx.company = 'DealCalc';
  
  // Set layout
  pptx.layout = 'LAYOUT_16x9';
  
  // Create slides
  createTitleSlide(pptx, data);
  createMetricsSlide(pptx, data);
  createWarningsSlide(pptx, data);
  createSourcesUsesSlide(pptx, data);
  createCashFlowSlide(pptx, data);
  
  // Add sensitivity slides
  if (data.sensitivityTables) {
    data.sensitivityTables.forEach(table => {
      createSensitivitySlide(pptx, table);
    });
  }
  
  createDisclaimerSlide(pptx, data);
  
  // Download
  await pptx.writeFile({ fileName: `dealcalc-${data.calculatorType}-presentation.pptx` });
}
