import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Share2,
  Copy,
  Check,
  Mail,
  Link as LinkIcon,
  X,
} from "lucide-react";
import type {
  LeaseRedlineResponse,
  RevisionDecision,
} from "@/lib/lease-redline/types";
import { DOCUMENT_TYPE_LABELS } from "@/lib/lease-redline/types";

interface ShareDialogProps {
  response: LeaseRedlineResponse;
  decisions: RevisionDecision[];
  onClose: () => void;
}

export function ShareDialog({
  response,
  decisions,
  onClose,
}: ShareDialogProps) {
  const [recipientEmail, setRecipientEmail] = useState("");
  const [message, setMessage] = useState("");
  const [includeChat, setIncludeChat] = useState(true);
  const [copied, setCopied] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  const buildShareableText = (): string => {
    const lines: string[] = [];
    lines.push(`LEASE REDLINE ANALYSIS — ${DOCUMENT_TYPE_LABELS[response.documentType]}`);
    lines.push(`Date: ${new Date().toLocaleDateString()}`);
    lines.push("");

    if (message) {
      lines.push(`Note from sender: ${message}`);
      lines.push("");
    }

    if (response.summary) {
      lines.push("EXECUTIVE SUMMARY:");
      lines.push(response.summary);
      lines.push("");
    }

    if (response.riskFlags.length > 0) {
      lines.push("RISK FLAGS:");
      response.riskFlags.forEach((f) => lines.push(`  - ${f}`));
      lines.push("");
    }

    lines.push(`REVISIONS: ${response.revisions.length} total`);
    const accepted = decisions.filter((d) => d === "accepted").length;
    const rejected = decisions.filter((d) => d === "rejected").length;
    lines.push(`  Accepted: ${accepted} | Rejected: ${rejected} | Pending: ${decisions.length - accepted - rejected}`);
    lines.push("");

    response.revisions.forEach((rev, i) => {
      const status = decisions[i] || "pending";
      lines.push(`--- #${rev.clauseNumber} [${(rev.riskLevel || "low").toUpperCase()}] [${status.toUpperCase()}] ---`);
      lines.push(`Category: ${rev.category || "other"}`);
      lines.push(`Rationale: ${rev.reason}`);
      lines.push(`Original: ${rev.originalLanguage.slice(0, 200)}...`);
      lines.push(`Revised: ${rev.cleanReplacement.slice(0, 200)}...`);
      lines.push("");
    });

    lines.push("---");
    lines.push("Generated by TheDealCalc Lease Redlining Agent");
    lines.push("This does not constitute legal advice.");

    return lines.join("\n");
  };

  const handleCopyLink = async () => {
    const text = buildShareableText();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available
    }
  };

  const handleEmailShare = () => {
    const subject = `Lease Redline Analysis — ${DOCUMENT_TYPE_LABELS[response.documentType]}`;
    const body = buildShareableText();
    const mailtoUrl = `mailto:${encodeURIComponent(recipientEmail)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoUrl, "_blank");
    setEmailSent(true);
    setTimeout(() => setEmailSent(false), 3000);
  };

  const isValidEmail = recipientEmail.includes("@") && recipientEmail.includes(".");

  return (
    <Card className="border-primary/20">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <Share2 className="h-4 w-4 text-primary" />
            Share Analysis
          </CardTitle>
          <Button variant="ghost" size="sm" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Personal message */}
        <div className="space-y-2">
          <Label>Add a note (optional)</Label>
          <Textarea
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            placeholder="Add context for the recipient..."
            className="min-h-[60px] text-sm"
            maxLength={500}
          />
        </div>

        {/* Copy to clipboard */}
        <Button variant="outline" className="w-full" onClick={handleCopyLink}>
          {copied ? (
            <>
              <Check className="h-4 w-4" />
              Copied to Clipboard
            </>
          ) : (
            <>
              <Copy className="h-4 w-4" />
              Copy Full Analysis
            </>
          )}
        </Button>

        {/* Email share */}
        <div className="space-y-2">
          <Label>Email to colleague or counsel</Label>
          <div className="flex gap-2">
            <input
              type="email"
              value={recipientEmail}
              onChange={(e) => setRecipientEmail(e.target.value)}
              placeholder="attorney@firm.com"
              className="flex-1 px-3 py-2 text-sm border rounded-md bg-background"
            />
            <Button
              onClick={handleEmailShare}
              disabled={!isValidEmail}
              size="sm"
            >
              {emailSent ? (
                <Check className="h-4 w-4" />
              ) : (
                <Mail className="h-4 w-4" />
              )}
              Send
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            Opens your default email client with the analysis pre-filled.
          </p>
        </div>

        {/* Stats */}
        <div className="text-xs text-muted-foreground border-t pt-3">
          Sharing {response.revisions.length} revisions, {response.riskFlags.length} risk flags
          {includeChat ? ", with chat history" : ""}
        </div>
      </CardContent>
    </Card>
  );
}
